version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - .:/opt/app
        environment:
            - ENVIRONMENT=staging
            - API_BASE_URL=http://localhost:9000
        ports:
            - "8080:8080"

    postgres_db:
        image: postgres:14.6-alpine
        restart: always
        environment:
            - DATABASE_CONNECTION_URL=postgres://postgres:postgres@postgres_db:5432/genai?ssslmode=disables&search_path=genai
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=genai
        volumes:
            - ./internal/db/init.sql:/docker-entrypoint-initdb.d/db.sql
        ports:
            - "5432:5432"
